channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9.5
  - pytorch==1.8.1
  - torchvision==0.9.1
  - pillow==8.3.1
  - tqdm==4.63.1
  - mlflow==1.24.0
  - yapf==0.31.0
  - pylint==2.12.1
  - ipykernel==6.13.0
  - pip==22.0.4
  - pip:
      - azure-ml==0.0.1
      - azureml-mlflow==1.41.0
      - azureml.core
