channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pillow==9.0.1
  - tqdm==4.64.0
  - mlflow==1.26.0
  - yapf==0.31.0
  - pylint==2.12.2
  - ipykernel==6.9.1
  - pip==20.2.4
  - pip:
      - azure-ml==0.0.1
      - azureml-mlflow==1.41.0
      - azureml-core==1.41.0
